#!/bin/sh
if [ -f ~/.bashrc ]; then
	rm ~/.bashrc
fi
ln -s ~/dotfiles/.bashrc ~/.bashrc

if [ -f ~/.tmux.conf ]; then
	rm ~/.tmux.conf
fi
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf

# rm current vim if exists
if [ -d ~/.vim ]; then
	rm -rf ~/.vim
	mkdir ~/.vim
fi

if [ -f ~/.vimrc ]; then
	rm ~/.vimrc
fi

ln -s ~/dotfiles/.vimrc
if [ ! -d ~/.vim/colors ]; then
	mkdir ~/.vim/colors
fi
cp -v ~/dotfiles/colors/*.vim ~/.vim/colors


/usr/bin/git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall
